# 1) 빌드
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# 2) 서빙
FROM nginx:stable-alpine
COPY --from=builder /app/dist/ /usr/share/nginx/html/
COPY default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
