# 1) 빌드
FROM node:18-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

# 2) 서빙
FROM nginx:stable-alpine
COPY --from=builder /app/dist/ /usr/share/nginx/html/
COPY frontend/default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
