services:
  itsm-mysql:
    container_name: itsm-mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dkdlxltmakxm1!
      - TZ=Asia/Seoul
    volumes:
      - itsm-mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "--character-set-server=utf8mb4"
    networks:
      - itsm-network

  itsm-backend:
    container_name: itsm-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "9999:9999"
    volumes:
      - /opt/profileMnt/uploads/images:/app/uploads/images
      - /opt/profileMnt/uploads/excel:/app/uploads/excel
    depends_on:
      - itsm-mysql
    networks:
      - itsm-network

  itsm-frontend:
    container_name: itsm-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "99:80"
    volumes:
      - /opt/profileMnt/uploads/images:/app/uploads/images
      - /opt/profileMnt/uploads/excel:/app/uploads/excel
    depends_on:
      - itsm-backend
    networks:
      - itsm-network

volumes:
  itsm-mysql:

networks:
  itsm-network:
    driver: bridge
