spring:
  application:
    name: profileMnt
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://mysqlDB:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: itsmart
    password: dkdlxltmakxm1!
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:sqlMapper/*.xml
  type-aliases-package: kr.co.itsm.profileMnt.vo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: false
management.endpoints.web.exposure.exclude: "*"

logging:
  level:
    kr.co.itsm.profileMnt: debug
    kr.co.itsm.profileMnt.mapper: TRACE
    org.springframework.web.servlet: debug

# Spring Boot Port setting(=Docker container port)
server:
  port: 9999

file:
  upload-photo-dir: /opt/profileMnt/uploads/images
  upload-excel-dir: /opt/profileMnt/uploads/excel
